import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(dirname, "..", "..");
const jsonPath = path.join(dirname, "output", "wordpress-export.json");
const mediaSrc = path.join(dirname, "output", "media");
const mediaDest = path.join(repoRoot, "client", "public", "wp-media");
const wpBlogsPath = path.join(repoRoot, "client", "src", "data", "wpBlogs.js");

function serialize(value) {
  return JSON.stringify(value, null, 2);
}

async function importWordpress() {
  const apply = process.argv.includes("--apply");
  let raw;

  try {
    raw = await fs.readFile(jsonPath, "utf8");
  } catch {
    throw new Error("No output/wordpress-export.json yet. Run `npm run export` first.");
  }

  const payload = JSON.parse(raw);
  const posts = payload.items.filter((item) => item.type === "post");
  const pages = payload.items.filter((item) => item.type === "page");

  console.log(`Review file: ${jsonPath}`);
  console.log(`Posts: ${posts.length}`);
  console.log(`Pages: ${pages.length} (kept in JSON only — React pages stay as designed components)`);
  console.log("Post slugs:");
  for (const post of posts) {
    console.log(`  /blogs/${post.slug} — ${post.title}`);
  }

  const file = `// Generated by scripts/wp-export/import.js. Review before shipping.
const wpBlogs = ${serialize(
    posts.map((post, index) => ({
      id: 1000 + index,
      slug: post.slug,
      image: post.featuredImage || "/wp-media/placeholder.jpg",
      category: post.category,
      title: post.title,
      description: post.excerpt,
      date: post.date,
      read: post.read,
      htmlContent: post.html,
      sections: post.sections,
    }))
  )};

export default wpBlogs;
`;

  if (!apply) {
    console.log("\nDry run. Re-run with --apply to write:");
    console.log(`  ${wpBlogsPath}`);
    console.log(`  ${mediaDest}`);
    return;
  }

  await fs.mkdir(mediaDest, { recursive: true });
  try {
    const files = await fs.readdir(mediaSrc);
    for (const name of files) {
      await fs.copyFile(path.join(mediaSrc, name), path.join(mediaDest, name));
    }
    console.log(`Copied ${files.length} images to client/public/wp-media/`);
  } catch {
    console.log("No output/media directory — skipping images");
  }

  await fs.writeFile(wpBlogsPath, file);
  console.log(`Wrote ${wpBlogsPath}`);
}

importWordpress().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
